Rebuild town center
alistair-jah/legacy-age3-ai pull request #1
Opened 2022-08-20 10:57 UTC by lanfranconi

I brought back the `tcMonitor` rule to make explorer units rebuild the town center if there's no more town center.

2022-08-20 12:07 UTC, alistair-jah requested changes
Just a tiny little bit more tweaks and you're good to go 👍

2022-08-20 12:07 UTC, alistair-jah commented on AI3/aiMain.xs
> +    aiPlanSetVariableVector(buildPlan, cBuildPlanCenterPosition, 0, kbBaseGetLocation(cMyID, kbBaseGetMainID(cMyID)));
Radius should be fixed to something like 80~100 meters, which is roughly twice the surface of the default TC LOS. We don't want TC's to be built too far from the main base, even in the case where the build plans fails frequently.

2022-08-20 12:39 UTC, lanfranconi commented on AI3/aiMain.xs
> +    switch (kbGetCiv())
Some campaign heroes can't build anything, so this section makes sense. But I guess all these explorer units should be added to the plan regardless of the civilization. I'm going to do that, actually.

2022-08-21 06:40 UTC, alistair-jah commented on AI3/aiMain.xs
> +    switch (kbGetCiv())
Ah, yeah, I forgot lol

Alright, good job 👌 I'm gonna add you directly as a contributor and co-author. What do you think?

2022-08-21 06:43 UTC, alistair-jah approved these changes

2022-08-21 06:44 UTC, merged